function [out1,j_out1,h_out1] = sys_9af7d90b1ebeb21457a641b0568c1e01(in1,in2,in3)
%SYS_9AF7D90B1EBEB21457A641B0568C1E01
%    [OUT1,J_OUT1,H_OUT1] = SYS_9AF7D90B1EBEB21457A641B0568C1E01(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    30-Mar-2022 20:32:28

in2val7 = in2(7,:);
in2val8 = in2(8,:);
in2val9 = in2(9,:);
in2val10 = in2(10,:);
out1 = in2val7.^2+in2val8.^2+in2val9.^2+in2val10.^2;
if nargout > 1
    j_out1 = [0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,in2val7.*2.0,in2val8.*2.0,in2val9.*2.0,in2val10.*2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0];
end
if nargout > 2
    h_out1 = zeros(0,0);
end

end
