function [out1,j_out1,h_out1] = sys_5e1f66248f2d758c6079317fe4952fae(in1,in2,in3)
%SYS_5E1F66248F2D758C6079317FE4952FAE
%    [OUT1,J_OUT1,H_OUT1] = SYS_5E1F66248F2D758C6079317FE4952FAE(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    30-Mar-2022 20:42:20

in2val4 = in2(4,:);
in2val5 = in2(5,:);
in2val6 = in2(6,:);
in2val7 = in2(7,:);
in2val8 = in2(8,:);
in2val9 = in2(9,:);
in2val10 = in2(10,:);
out1 = [in2val7.^2+in2val8.^2+in2val9.^2+in2val10.^2;in2val4.^2+in2val5.^2+in2val6.^2];
if nargout > 1
    j_out1 = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,in2val4.*2.0,0.0,in2val5.*2.0,0.0,in2val6.*2.0,in2val7.*2.0,0.0,in2val8.*2.0,0.0,in2val9.*2.0,0.0,in2val10.*2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[2,26]);
end
if nargout > 2
    h_out1 = zeros(0,0);
end

end
