function [ statesdot, j_statesdot ] = mb_fm_mex_aircraft( states, controls )
%mb_fm_mex_aircraft
% File automatically generated by FALCON.m

%=== Extract Data From Input ==============================================
x_E = states(1);
y_E = states(2);
z_E = states(3);
vx_E = states(4);
vy_E = states(5);
vz_E = states(6);
e0 = states(7);
e1 = states(8);
e2 = states(9);
e3 = states(10);
W_P = states(11);
phidot_P = states(12);
Js_P = states(13);
n_P = states(14);
phidotcom_P = controls(1);
Jscom_P = controls(2);
ncom_P = controls(3);

%=== Jacobians and Hessians ===============================================
j_x_E = zeros(1,17);
j_x_E(:,1) = eye(1);
j_y_E = zeros(1,17);
j_y_E(:,2) = eye(1);
j_z_E = zeros(1,17);
j_z_E(:,3) = eye(1);
j_vx_E = zeros(1,17);
j_vx_E(:,4) = eye(1);
j_vy_E = zeros(1,17);
j_vy_E(:,5) = eye(1);
j_vz_E = zeros(1,17);
j_vz_E(:,6) = eye(1);
j_e0 = zeros(1,17);
j_e0(:,7) = eye(1);
j_e1 = zeros(1,17);
j_e1(:,8) = eye(1);
j_e2 = zeros(1,17);
j_e2(:,9) = eye(1);
j_e3 = zeros(1,17);
j_e3(:,10) = eye(1);
j_W_P = zeros(1,17);
j_W_P(:,11) = eye(1);
j_phidot_P = zeros(1,17);
j_phidot_P(:,12) = eye(1);
j_Js_P = zeros(1,17);
j_Js_P(:,13) = eye(1);
j_n_P = zeros(1,17);
j_n_P(:,14) = eye(1);
j_phidotcom_P = zeros(1,17);
j_phidotcom_P(:,15) = eye(1);
j_Jscom_P = zeros(1,17);
j_Jscom_P(:,16) = eye(1);
j_ncom_P = zeros(1,17);
j_ncom_P(:,17) = eye(1);

% Combine Variables to states
states = [x_E; y_E; z_E; vx_E; vy_E; vz_E; e0; e1; e2; e3; W_P; phidot_P; Js_P; n_P];
j_states = [j_x_E(1,:); j_y_E(1,:); j_z_E(1,:); j_vx_E(1,:); j_vy_E(1,:); j_vz_E(1,:); j_e0(1,:); j_e1(1,:); j_e2(1,:); j_e3(1,:); j_W_P(1,:); j_phidot_P(1,:); j_Js_P(1,:); j_n_P(1,:)];

% Combine Variables to controls
controls = [phidotcom_P; Jscom_P; ncom_P];
j_controls = [j_phidotcom_P(1,:); j_Jscom_P(1,:); j_ncom_P(1,:)];

%=== Write Constants ======================================================
