function [ statesdot, outputs, j_statesdot, j_outputs ] = mb_OptimalManeuver(states, controls)
%mb_OptimalManeuver
% File automatically generated by FALCON.m

%=== Extract Data From Input ==============================================
x_E = states(1);
y_E = states(2);
z_E = states(3);
v = states(4);
e0 = states(5);
e1 = states(6);
e2 = states(7);
e3 = states(8);
W = states(9);
P = states(10);
Js = states(11);
n = states(12);
Pcom = controls(1);
Jscom = controls(2);
ncom = controls(3);

%=== Jacobians and Hessians ===============================================
j_states = zeros(12, 15);
j_states(:, 1 : 12) = eye(12);
j_x_E = j_states(1, :);
j_y_E = j_states(2, :);
j_z_E = j_states(3, :);
j_v = j_states(4, :);
j_e0 = j_states(5, :);
j_e1 = j_states(6, :);
j_e2 = j_states(7, :);
j_e3 = j_states(8, :);
j_W = j_states(9, :);
j_P = j_states(10, :);
j_Js = j_states(11, :);
j_n = j_states(12, :);
j_controls = zeros(3, 15);
j_controls(:, 13 : 15) = eye(3);
j_Pcom = j_controls(1, :);
j_Jscom = j_controls(2, :);
j_ncom = j_controls(3, :);

%=== Write Constants ======================================================

%=== Subsystem sysPositionPropagation =====================================

% Defined at mainManeuverSim (mainManeuverSim.m:49)

% Call sys_9ad26b3366587637edbbdc61512a5773_jac
[ rdot_E, phi, gamma, psi, j_rdot_E, j_phi, j_gamma, j_psi ] = sys_9ad26b3366587637edbbdc61512a5773_jac(v, e0, e1, e2, e3);

% Hessian Jacobian for sys_9ad26b3366587637edbbdc61512a5773_jac
tmp_j_input_sys_9ad26b3366587637edbbdc61512a5773_jac = [j_v; j_e0; j_e1; j_e2; j_e3];

% Calculation of Jacobian with respect to function global input for sys_9ad26b3366587637edbbdc61512a5773_jac
j_rdot_E = j_rdot_E * tmp_j_input_sys_9ad26b3366587637edbbdc61512a5773_jac;
j_phi = j_phi * tmp_j_input_sys_9ad26b3366587637edbbdc61512a5773_jac;
j_gamma = j_gamma * tmp_j_input_sys_9ad26b3366587637edbbdc61512a5773_jac;
j_psi = j_psi * tmp_j_input_sys_9ad26b3366587637edbbdc61512a5773_jac;

%=== Subsystem sysAeroCalc ================================================

% Defined at mainManeuverSim (mainManeuverSim.m:54)

% Call sys_abd1dd15ef234fda3363cddb8e59878b_jac
[ alpha, CL, CD, j_alpha, j_CL, j_CD ] = sys_abd1dd15ef234fda3363cddb8e59878b_jac(z_E, v, n, W);

% Hessian Jacobian for sys_abd1dd15ef234fda3363cddb8e59878b_jac
tmp_j_input_sys_abd1dd15ef234fda3363cddb8e59878b_jac = [j_z_E; j_v; j_n; j_W];

% Calculation of Jacobian with respect to function global input for sys_abd1dd15ef234fda3363cddb8e59878b_jac
j_alpha = j_alpha * tmp_j_input_sys_abd1dd15ef234fda3363cddb8e59878b_jac;
j_CL = j_CL * tmp_j_input_sys_abd1dd15ef234fda3363cddb8e59878b_jac;
j_CD = j_CD * tmp_j_input_sys_abd1dd15ef234fda3363cddb8e59878b_jac;

%=== Subsystem sysThrustCalc ==============================================

% Defined at mainManeuverSim (mainManeuverSim.m:59)

% Call sys_674cfd48df4a3213d3be218b57f43a70_jac
[ T, TSFC, j_T, j_TSFC ] = sys_674cfd48df4a3213d3be218b57f43a70_jac(z_E, v, Js);

% Hessian Jacobian for sys_674cfd48df4a3213d3be218b57f43a70_jac
tmp_j_input_sys_674cfd48df4a3213d3be218b57f43a70_jac = [j_z_E; j_v; j_Js];

% Calculation of Jacobian with respect to function global input for sys_674cfd48df4a3213d3be218b57f43a70_jac
j_T = j_T * tmp_j_input_sys_674cfd48df4a3213d3be218b57f43a70_jac;
j_TSFC = j_TSFC * tmp_j_input_sys_674cfd48df4a3213d3be218b57f43a70_jac;

%=== Subsystem sysTranslationPropagation ==================================

% Defined at mainManeuverSim (mainManeuverSim.m:64)

% Call sys_5fe1108a3442fb37379a14c6cc0d697e_jac
[ vdot, edot_P, Wdot, ng, Wneg, j_vdot, j_edot_P, j_Wdot, j_ng, j_Wneg ] = sys_5fe1108a3442fb37379a14c6cc0d697e_jac(z_E, v, e0, e1, e2, e3, W, P, T, CD, CL, alpha, TSFC);

% Hessian Jacobian for sys_5fe1108a3442fb37379a14c6cc0d697e_jac
tmp_j_input_sys_5fe1108a3442fb37379a14c6cc0d697e_jac = [j_z_E; j_v; j_e0; j_e1; j_e2; j_e3; j_W; j_P; j_T; j_CD; j_CL; j_alpha; j_TSFC];

% Calculation of Jacobian with respect to function global input for sys_5fe1108a3442fb37379a14c6cc0d697e_jac
j_vdot = j_vdot * tmp_j_input_sys_5fe1108a3442fb37379a14c6cc0d697e_jac;
j_edot_P = j_edot_P * tmp_j_input_sys_5fe1108a3442fb37379a14c6cc0d697e_jac;
j_Wdot = j_Wdot * tmp_j_input_sys_5fe1108a3442fb37379a14c6cc0d697e_jac;
j_ng = j_ng * tmp_j_input_sys_5fe1108a3442fb37379a14c6cc0d697e_jac;
j_Wneg = j_Wneg * tmp_j_input_sys_5fe1108a3442fb37379a14c6cc0d697e_jac;

%=== Subsystem sysCommandsDelay ===========================================

% Defined at mainManeuverSim (mainManeuverSim.m:69)

% Call sys_2e11da000b4bbadf99d6dd9a0951f18b_jac
[ Pdot, Jsdot, ndot, j_Pdot, j_Jsdot, j_ndot ] = sys_2e11da000b4bbadf99d6dd9a0951f18b_jac(P, Js, n, Pcom, Jscom, ncom);

% Hessian Jacobian for sys_2e11da000b4bbadf99d6dd9a0951f18b_jac
tmp_j_input_sys_2e11da000b4bbadf99d6dd9a0951f18b_jac = [j_P; j_Js; j_n; j_Pcom; j_Jscom; j_ncom];

% Calculation of Jacobian with respect to function global input for sys_2e11da000b4bbadf99d6dd9a0951f18b_jac
j_Pdot = j_Pdot * tmp_j_input_sys_2e11da000b4bbadf99d6dd9a0951f18b_jac;
j_Jsdot = j_Jsdot * tmp_j_input_sys_2e11da000b4bbadf99d6dd9a0951f18b_jac;
j_ndot = j_ndot * tmp_j_input_sys_2e11da000b4bbadf99d6dd9a0951f18b_jac;

%=== Split Variable rdot_E ================================================
xdot_E = rdot_E(1.');
j_xdot_E = [j_rdot_E(1,:)];
ydot_E = rdot_E(2.');
j_ydot_E = [j_rdot_E(2,:)];
zdot_E = rdot_E(3.');
j_zdot_E = [j_rdot_E(3,:)];

%=== Split Variable edot_P ================================================
e0dot = edot_P(1.');
j_e0dot = [j_edot_P(1,:)];
e1dot = edot_P(2.');
j_e1dot = [j_edot_P(2,:)];
e2dot = edot_P(3.');
j_e2dot = [j_edot_P(3,:)];
e3dot = edot_P(4.');
j_e3dot = [j_edot_P(4,:)];

% Combine Variables to statesdot
statesdot = [xdot_E; ydot_E; zdot_E; vdot; e0dot; e1dot; e2dot; e3dot; Wdot; Pdot; Jsdot; ndot];
j_statesdot = [
    j_xdot_E(1, :)
    j_ydot_E(1, :)
    j_zdot_E(1, :)
    j_vdot(1, :)
    j_e0dot(1, :)
    j_e1dot(1, :)
    j_e2dot(1, :)
    j_e3dot(1, :)
    j_Wdot(1, :)
    j_Pdot(1, :)
    j_Jsdot(1, :)
    j_ndot(1, :)
];

% Combine Variables to outputs
outputs = [phi; gamma; psi; alpha; CL; CD; T; TSFC; ng; Wneg];
j_outputs = [
    j_phi(1, :)
    j_gamma(1, :)
    j_psi(1, :)
    j_alpha(1, :)
    j_CL(1, :)
    j_CD(1, :)
    j_T(1, :)
    j_TSFC(1, :)
    j_ng(1, :)
    j_Wneg(1, :)
];

end
