function [out1,out2,out3,out4,out5,j_out1,j_out2,j_out3,j_out4,j_out5,h_out1,h_out2,h_out3,h_out4,h_out5] = sys_5fe1108a3442fb37379a14c6cc0d697e_jac(in1val1,in2val1,in3val1,in4val1,in5val1,in6val1,in7val1,in8val1,in9val1,in10val1,in11val1,in12val1,in13val1)
%SYS_5FE1108A3442FB37379A14C6CC0D697E_JAC
%    [OUT1,OUT2,OUT3,OUT4,OUT5,J_OUT1,J_OUT2,J_OUT3,J_OUT4,J_OUT5,H_OUT1,H_OUT2,H_OUT3,H_OUT4,H_OUT5] = SYS_5FE1108A3442FB37379A14C6CC0D697E_JAC(IN1VAL1,IN2VAL1,IN3VAL1,IN4VAL1,IN5VAL1,IN6VAL1,IN7VAL1,IN8VAL1,IN9VAL1,IN10VAL1,IN11VAL1,IN12VAL1,IN13VAL1)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    26-Jan-2023 16:21:18

%Generated using CreateGradient
%Input dimensions : {[1 1], [1 1], [1 1], [1 1], [1 1], [1 1], [1 1], [1 1], [1 1], [1 1], [1 1], [1 1], [1 1]}
%Derivative inputs: [true true true true true true true true true true true true true]
%DerivativeOrder  : 1
%Output dimensions: {[1 1], [4 1], [1 1], [1 1], [1 1]}
%Constant outputs : [false false false false false]
t2 = cos(in12val1);
t3 = sin(in12val1);
t4 = in2val1.^2;
t5 = in3val1.^2;
t6 = in4val1.^2;
t7 = in5val1.^2;
t8 = in6val1.^2;
t9 = in3val1.*in5val1.*2.0;
t10 = in4val1.*in6val1.*2.0;
t13 = 1.0./in2val1;
t15 = 1.0./in7val1;
t18 = in8val1./2.0;
t23 = in3val1.*in4val1.*(9.81e+2./5.0e+1);
t24 = in5val1.*in6val1.*(9.81e+2./5.0e+1);
t27 = in1val1.*2.255769564462953e-5;
t11 = in9val1.*t2;
t12 = in9val1.*t3;
t14 = 1.0./t4;
t16 = t15.^2;
t17 = -t10;
t19 = -t6;
t20 = -t7;
t22 = -t18;
t28 = t27+1.0;
t29 = in3val1.*in5val1.*t13.*(9.81e+2./1.0e+2);
t30 = in3val1.*in6val1.*t13.*(9.81e+2./1.0e+2);
t31 = in4val1.*in5val1.*t13.*(9.81e+2./1.0e+2);
t32 = in4val1.*in6val1.*t13.*(9.81e+2./1.0e+2);
t33 = t5.*t13.*(9.81e+2./1.0e+2);
t34 = t6.*t13.*(9.81e+2./1.0e+2);
t35 = t7.*t13.*(9.81e+2./1.0e+2);
t36 = t8.*t13.*(9.81e+2./1.0e+2);
t42 = t23+t24;
t21 = -t11;
t25 = t9+t17;
t37 = -t30;
t38 = -t31;
t39 = -t32;
t40 = t5+t8+t19+t20;
t44 = t28.^3.258643795229161;
t45 = t28.^4.258643795229161;
t46 = (t13.*t42)./2.0;
t26 = in7val1.*t25;
t41 = in7val1.*t40;
t47 = -t46;
t48 = t29+t39;
t49 = in10val1.*t4.*t45.*1.707407859219665e+1;
t50 = in11val1.*t4.*t45.*1.707407859219665e+1;
t43 = -t41;
t51 = t12+t50;
t52 = t21+t26+t49;
out1 = t15.*t52.*(-9.81e+2./1.0e+2);
if nargout > 1
    t53 = t43+t51;
    t54 = t13.*t15.*t53.*(9.81e+2./2.0e+2);
    out2 = [in4val1.*in8val1.*(-1.0./2.0)-(in6val1.*t13.*t42)./2.0-in5val1.*t13.*t15.*t53.*(9.81e+2./2.0e+2);in3val1.*t18+in5val1.*t46-in6val1.*t13.*t15.*t53.*(9.81e+2./2.0e+2);in6val1.*t18+in3val1.*t54-(in4val1.*t13.*t42)./2.0;in5val1.*in8val1.*(-1.0./2.0)+in3val1.*t46+in4val1.*t54];
end
if nargout > 2
    out3 = -in9val1.*in13val1;
end
if nargout > 3
    out4 = t15.*t51;
end
if nargout > 4
    out5 = -in7val1;
end
if nargout > 5
    mt1 = [in10val1.*t4.*t15.*t44.*(-1.60906034646792e-2),in2val1.*in10val1.*t15.*t45.*(-3.349934219788982e+2),in5val1.*(-9.81e+2./5.0e+1),in6val1.*(9.81e+2./5.0e+1),in3val1.*(-9.81e+2./5.0e+1),in4val1.*(9.81e+2./5.0e+1),t15.*t25.*(-9.81e+2./1.0e+2)+t16.*t52.*(9.81e+2./1.0e+2),0.0,t2.*t15.*(9.81e+2./1.0e+2)];
    mt2 = [t4.*t15.*t45.*(-1.674967109894491e+2),0.0,t12.*t15.*(-9.81e+2./1.0e+2),0.0];
    j_out1 = reshape([mt1,mt2],1,13);
end
if nargout > 6
    t55 = -t54;
    mt3 = [in2val1.*in5val1.*in11val1.*t15.*t44.*(-8.0453017323396e-3),in2val1.*in6val1.*in11val1.*t15.*t44.*(-8.0453017323396e-3),in2val1.*in3val1.*in11val1.*t15.*t44.*8.0453017323396e-3];
    mt4 = [in2val1.*in4val1.*in11val1.*t15.*t44.*8.0453017323396e-3,(in6val1.*t14.*t42)./2.0-in5val1.*in11val1.*t15.*t45.*1.674967109894491e+2+in5val1.*t14.*t15.*t53.*(9.81e+2./2.0e+2),in5val1.*t14.*t42.*(-1.0./2.0)-in6val1.*in11val1.*t15.*t45.*1.674967109894491e+2+in6val1.*t14.*t15.*t53.*(9.81e+2./2.0e+2)];
    mt5 = [(in4val1.*t14.*t42)./2.0+in3val1.*in11val1.*t15.*t45.*1.674967109894491e+2-in3val1.*t14.*t15.*t53.*(9.81e+2./2.0e+2),in3val1.*t14.*t42.*(-1.0./2.0)+in4val1.*in11val1.*t15.*t45.*1.674967109894491e+2-in4val1.*t14.*t15.*t53.*(9.81e+2./2.0e+2),t48,t18+t30+t31,-t33-t34+t54,t46,t22+t37+t38,t48,t47,t33+t34+t54,-t35-t36+t55,t46,t48,t22+t30+t31,t47,t35+t36+t55,t18+t37+t38,t48];
    mt6 = [in5val1.*t13.*t15.*t40.*(9.81e+2./2.0e+2)+in5val1.*t13.*t16.*t53.*(9.81e+2./2.0e+2),in6val1.*t13.*t15.*t40.*(9.81e+2./2.0e+2)+in6val1.*t13.*t16.*t53.*(9.81e+2./2.0e+2),in3val1.*t13.*t15.*t40.*(-9.81e+2./2.0e+2)-in3val1.*t13.*t16.*t53.*(9.81e+2./2.0e+2),in4val1.*t13.*t15.*t40.*(-9.81e+2./2.0e+2)-in4val1.*t13.*t16.*t53.*(9.81e+2./2.0e+2),in4val1.*(-1.0./2.0),in3val1./2.0,in6val1./2.0,in5val1.*(-1.0./2.0),in5val1.*t3.*t13.*t15.*(-9.81e+2./2.0e+2),in6val1.*t3.*t13.*t15.*(-9.81e+2./2.0e+2),in3val1.*t3.*t13.*t15.*(9.81e+2./2.0e+2),in4val1.*t3.*t13.*t15.*(9.81e+2./2.0e+2),0.0,0.0,0.0,0.0];
    mt7 = [in2val1.*in5val1.*t15.*t45.*(-8.374835549472455e+1),in2val1.*in6val1.*t15.*t45.*(-8.374835549472455e+1),in2val1.*in3val1.*t15.*t45.*8.374835549472455e+1,in2val1.*in4val1.*t15.*t45.*8.374835549472455e+1,in5val1.*t11.*t13.*t15.*(-9.81e+2./2.0e+2)];
    mt8 = [in6val1.*t11.*t13.*t15.*(-9.81e+2./2.0e+2),in3val1.*t11.*t13.*t15.*(9.81e+2./2.0e+2),in4val1.*t11.*t13.*t15.*(9.81e+2./2.0e+2),0.0,0.0,0.0,0.0];
    j_out2 = reshape([mt3,mt4,mt5,mt6,mt7,mt8],4,13);
end
if nargout > 7
    j_out3 = [0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-in13val1,0.0,0.0,0.0,-in9val1];
end
if nargout > 8
    j_out4 = [in11val1.*t4.*t15.*t44.*1.640224614136514e-3,in2val1.*in11val1.*t15.*t45.*3.414815718439329e+1,0.0,0.0,0.0,0.0,-t16.*t51,0.0,t3.*t15,0.0,t4.*t15.*t45.*1.707407859219665e+1,t11.*t15,0.0];
end
if nargout > 9
    j_out5 = [0.0,0.0,0.0,0.0,0.0,0.0,-1.0,0.0,0.0,0.0,0.0,0.0,0.0];
end
if nargout > 10
    h_out1 = zeros(0,0);
end
if nargout > 11
    h_out2 = zeros(0,0);
end
if nargout > 12
    h_out3 = zeros(0,0);
end
if nargout > 13
    h_out4 = zeros(0,0);
end
if nargout > 14
    h_out5 = zeros(0,0);
end

end  % sys_5fe1108a3442fb37379a14c6cc0d697e_jac
