function [out1,j_out1,h_out1] = sys_0161777937bf44977fdc9383fccad68d(in1val1,in2val1,in3val1,in4val1,in5val1,in6val1,in7val1)
%SYS_0161777937BF44977FDC9383FCCAD68D
%    [OUT1,J_OUT1,H_OUT1] = SYS_0161777937BF44977FDC9383FCCAD68D(IN1VAL1,IN2VAL1,IN3VAL1,IN4VAL1,IN5VAL1,IN6VAL1,IN7VAL1)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    27-Mar-2022 02:37:09

t2 = in2val1.^2;
t3 = in3val1.^2;
t4 = in4val1.^2;
t6 = in1val1.*2.255769564462953e-5;
t5 = t2+t3+t4;
t9 = t6+1.0;
t7 = 1.0./t5;
t10 = 1.0./t9.^4.258643795229161;
out1 = in5val1.*in7val1.*t7.*t10.*5.856831421972189e-2;
if nargout > 1
    t8 = t7.^2;
    mt1 = [in5val1.*in7val1.*t7.*1.0./t9.^5.258643795229161.*(-5.626376268150367e-6),in2val1.*in5val1.*in7val1.*t8.*t10.*(-1.171366284394438e-1),in3val1.*in5val1.*in7val1.*t8.*t10.*(-1.171366284394438e-1),in4val1.*in5val1.*in7val1.*t8.*t10.*(-1.171366284394438e-1)];
    mt2 = [in7val1.*t7.*t10.*5.856831421972189e-2,0.0,in5val1.*t7.*t10.*5.856831421972189e-2];
    j_out1 = reshape([mt1,mt2],1,7);
end
if nargout > 2
    h_out1 = zeros(0,0);
end

end
