function [out1,out2,out3,out4,j_out1,j_out2,j_out3,j_out4,h_out1,h_out2,h_out3,h_out4] = sys_9ad26b3366587637edbbdc61512a5773_jac(in1val1,in2val1,in3val1,in4val1,in5val1)
%SYS_9AD26B3366587637EDBBDC61512A5773_JAC
%    [OUT1,OUT2,OUT3,OUT4,J_OUT1,J_OUT2,J_OUT3,J_OUT4,H_OUT1,H_OUT2,H_OUT3,H_OUT4] = SYS_9AD26B3366587637EDBBDC61512A5773_JAC(IN1VAL1,IN2VAL1,IN3VAL1,IN4VAL1,IN5VAL1)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    26-Jan-2023 16:21:15

%Generated using CreateGradient
%Input dimensions : {[1 1], [1 1], [1 1], [1 1], [1 1]}
%Derivative inputs: [true true true true true]
%DerivativeOrder  : 1
%Output dimensions: {[3 1], [1 1], [1 1], [1 1]}
%Constant outputs : [false false false false]
t2 = in2val1.^2;
t3 = in3val1.^2;
t4 = in4val1.^2;
t5 = in5val1.^2;
t6 = in1val1.*in2val1.*2.0;
t7 = in1val1.*in3val1.*2.0;
t8 = in1val1.*in4val1.*2.0;
t9 = in2val1.*in3val1.*2.0;
t10 = in1val1.*in5val1.*2.0;
t11 = in2val1.*in4val1.*2.0;
t12 = in2val1.*in5val1.*2.0;
t13 = in3val1.*in4val1.*2.0;
t14 = in3val1.*in5val1.*2.0;
t15 = in4val1.*in5val1.*2.0;
t16 = -t8;
t17 = -t14;
t18 = -t3;
t19 = -t4;
t20 = -t5;
t21 = t9+t15;
t22 = t12+t13;
t23 = t11+t17;
t24 = t21.^2;
t25 = t22.^2;
t29 = t2+t5+t18+t19;
t30 = t2+t3+t19+t20;
out1 = [in1val1.*t30;in1val1.*t22;-in1val1.*t23];
if nargout > 1
    out2 = atan2(in2val1.*in3val1.*2.0+in4val1.*in5val1.*2.0,t29);
end
if nargout > 2
    out3 = asin(t23);
end
if nargout > 3
    out4 = atan2(in2val1.*in5val1.*2.0+in3val1.*in4val1.*2.0,t30);
end
if nargout > 4
    j_out1 = reshape([t30,t22,-t11+t14,t6,t10,t16,t7,t8,t10,t16,t7,-t6,-t10,t6,t7],[3,5]);
end
if nargout > 5
    t26 = t23.^2;
    t31 = t29.^2;
    t32 = t30.^2;
    t34 = 1.0./t29;
    t35 = 1.0./t30;
    t27 = -t26;
    t36 = 1.0./t31;
    t37 = 1.0./t32;
    t38 = t24+t31;
    t39 = t25+t32;
    t28 = t27+1.0;
    t40 = 1.0./t38;
    j_out2 = [0.0,t31.*t40.*(in3val1.*t34.*2.0-in2val1.*t21.*t36.*2.0),t31.*t40.*(in2val1.*t34.*2.0+in3val1.*t21.*t36.*2.0),t31.*t40.*(in5val1.*t34.*2.0+in4val1.*t21.*t36.*2.0),t31.*t40.*(in4val1.*t34.*2.0-in5val1.*t21.*t36.*2.0)];
end
if nargout > 6
    t41 = 1.0./t39;
    t33 = 1.0./sqrt(t28);
    j_out3 = [0.0,in4val1.*t33.*2.0,in5val1.*t33.*-2.0,in2val1.*t33.*2.0,in3val1.*t33.*-2.0];
end
if nargout > 7
    j_out4 = [0.0,t32.*t41.*(in5val1.*t35.*2.0-in2val1.*t22.*t37.*2.0),t32.*t41.*(in4val1.*t35.*2.0-in3val1.*t22.*t37.*2.0),t32.*t41.*(in3val1.*t35.*2.0+in4val1.*t22.*t37.*2.0),t32.*t41.*(in2val1.*t35.*2.0+in5val1.*t22.*t37.*2.0)];
end
if nargout > 8
    h_out1 = zeros(0,0);
end
if nargout > 9
    h_out2 = zeros(0,0);
end
if nargout > 10
    h_out3 = zeros(0,0);
end
if nargout > 11
    h_out4 = zeros(0,0);
end

end  % sys_9ad26b3366587637edbbdc61512a5773_jac
