function [out1,out2,out3,j_out1,j_out2,j_out3,h_out1,h_out2,h_out3] = sys_6581733cc9ff0ec32f2da6105b085807(in1,in2)
%SYS_6581733CC9FF0EC32F2DA6105B085807
%    [OUT1,OUT2,OUT3,J_OUT1,J_OUT2,J_OUT3,H_OUT1,H_OUT2,H_OUT3] = SYS_6581733CC9FF0EC32F2DA6105B085807(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    25-Mar-2022 18:01:48

in1val3 = in1(3,:);
in1val4 = in1(4,:);
in2val1 = in2(1,:);
in2val2 = in2(2,:);
out1 = [in1val3.*cos(in1val4);in1val3.*sin(in1val4);in2val1;in2val2];
if nargout > 1
    out2 = in1val3.*sin(in1val4);
end
if nargout > 2
    out3 = in1val3+1.0;
end
if nargout > 3
    j_out1 = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,cos(in1val4),sin(in1val4),0.0,0.0,-in1val3.*sin(in1val4),in1val3.*cos(in1val4),0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0],[4,6]);
end
if nargout > 4
    j_out2 = [0.0,0.0,sin(in1val4),in1val3.*cos(in1val4),0.0,0.0];
end
if nargout > 5
    j_out3 = [0.0,0.0,1.0,0.0,0.0,0.0];
end
if nargout > 6
    h_out1 = zeros(0,0);
end
if nargout > 7
    h_out2 = zeros(0,0);
end
if nargout > 8
    h_out3 = zeros(0,0);
end

end
