function [out1,out2,j_out1,j_out2,h_out1,h_out2] = sys_674cfd48df4a3213d3be218b57f43a70_jac(in1val1,in2val1,in3val1)
%SYS_674CFD48DF4A3213D3BE218B57F43A70_JAC
%    [OUT1,OUT2,J_OUT1,J_OUT2,H_OUT1,H_OUT2] = SYS_674CFD48DF4A3213D3BE218B57F43A70_JAC(IN1VAL1,IN2VAL1,IN3VAL1)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    26-Jan-2023 16:21:17

%Generated using CreateGradient
%Input dimensions : {[1 1], [1 1], [1 1]}
%Derivative inputs: [true true true]
%DerivativeOrder  : 1
%Output dimensions: {[1 1], [1 1]}
%Constant outputs : [false true]
t2 = in1val1.*2.255769564462953e-5;
t3 = in1val1.*2.6117;
t4 = t2+1.0;
t6 = t3+1.1577867e+5;
t5 = t4.^4.258643795229161;
t7 = 1.0./sqrt(t6);
t8 = in2val1.*t7.*(7.0./2.0e+1);
t9 = t8+1.0;
out1 = in3val1.*t5.*t9.*8.898038991119867e+4;
if nargout > 1
    out2 = 2.138e-4;
end
if nargout > 2
    j_out1 = [in3val1.*t4.^3.258643795229161.*t9.*8.54791811574036-in2val1.*in3val1.*t5.*t7.^3.*4.066826475793857e+4,in3val1.*t5.*t7.*3.114313646891953e+4,t5.*t9.*8.898038991119867e+4];
end
if nargout > 3
    j_out2 = [0.0,0.0,0.0];
end
if nargout > 4
    h_out1 = zeros(0,0);
end
if nargout > 5
    h_out2 = zeros(0,0);
end

end  % sys_674cfd48df4a3213d3be218b57f43a70_jac
