function [ statesdot, outputs, j_statesdot, j_outputs ] = mb_fm_mex_source_car( states, controls )
%mb_fm_mex_source_car
% File automatically generated by FALCON.m

%=== Extract Data From Input ==============================================
x = states(1);
y = states(2);
V = states(3);
chi = states(4);
Vdot = controls(1);
chidot = controls(2);

%=== Jacobians and Hessians ===============================================
j_x = zeros(1,6);
j_x(:,1) = eye(1);
j_y = zeros(1,6);
j_y(:,2) = eye(1);
j_V = zeros(1,6);
j_V(:,3) = eye(1);
j_chi = zeros(1,6);
j_chi(:,4) = eye(1);
j_Vdot = zeros(1,6);
j_Vdot(:,5) = eye(1);
j_chidot = zeros(1,6);
j_chidot(:,6) = eye(1);

% Combine Variables to states
states = [x; y; V; chi];
j_states = [j_x(1,:); j_y(1,:); j_V(1,:); j_chi(1,:)];

% Combine Variables to controls
controls = [Vdot; chidot];
j_controls = [j_Vdot(1,:); j_chidot(1,:)];

%=== Write Constants ======================================================

%=== Call sys_6581733cc9ff0ec32f2da6105b085807 ============================
[statedottmp, dummyout, dummy1, j_statedottmp, j_dummyout, j_dummy1] = sys_6581733cc9ff0ec32f2da6105b085807(states, controls);

% Hessian Jacobian for sys_6581733cc9ff0ec32f2da6105b085807
tmp_j_input_sys_6581733cc9ff0ec32f2da6105b085807 = [j_states; j_controls];

% Calculation of Jacobian with respect to function global input for sys_6581733cc9ff0ec32f2da6105b085807
j_statedottmp = j_statedottmp * tmp_j_input_sys_6581733cc9ff0ec32f2da6105b085807;
j_dummyout = j_dummyout * tmp_j_input_sys_6581733cc9ff0ec32f2da6105b085807;
j_dummy1 = j_dummy1 * tmp_j_input_sys_6581733cc9ff0ec32f2da6105b085807;

% Combine Variables to statesdot
statesdot = [statedottmp];
j_statesdot = [j_statedottmp(1,:); j_statedottmp(2,:); j_statedottmp(3,:); j_statedottmp(4,:)];

% Combine Variables to outputs
outputs = [dummyout; dummy1];
j_outputs = [j_dummyout(1,:); j_dummy1(1,:)];

end
