function [out1,out2,out3,j_out1,j_out2,j_out3,h_out1,h_out2,h_out3] = sys_78b3198f4c5c63ce92673bb012e22e95_jac(in1val1,in2val1,in3val1,in4val1,in5val1,in6val1)
%SYS_78B3198F4C5C63CE92673BB012E22E95_JAC
%    [OUT1,OUT2,OUT3,J_OUT1,J_OUT2,J_OUT3,H_OUT1,H_OUT2,H_OUT3] = SYS_78B3198F4C5C63CE92673BB012E22E95_JAC(IN1VAL1,IN2VAL1,IN3VAL1,IN4VAL1,IN5VAL1,IN6VAL1)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    20-Jan-2023 14:00:09

%Generated using CreateGradient
%Input dimensions : {[1 1], [1 1], [1 1], [1 1], [1 1], [1 1]}
%Derivative inputs: [true true true true true true]
%DerivativeOrder  : 1
%Output dimensions: {[1 1], [1 1], [1 1]}
%Constant outputs : [false false false]
out1 = in1val1.*-5.0+in4val1.*5.0;
if nargout > 1
    out2 = in2val1.*-5.0+in5val1.*5.0;
end
if nargout > 2
    out3 = in3val1.*-5.0+in6val1.*5.0;
end
if nargout > 3
    j_out1 = [-5.0,0.0,0.0,5.0,0.0,0.0];
end
if nargout > 4
    j_out2 = [0.0,-5.0,0.0,0.0,5.0,0.0];
end
if nargout > 5
    j_out3 = [0.0,0.0,-5.0,0.0,0.0,5.0];
end
if nargout > 6
    h_out1 = zeros(0,0);
end
if nargout > 7
    h_out2 = zeros(0,0);
end
if nargout > 8
    h_out3 = zeros(0,0);
end

end  % sys_78b3198f4c5c63ce92673bb012e22e95_jac
