function [out1,out2,out3,out4,j_out1,j_out2,j_out3,j_out4,h_out1,h_out2,h_out3,h_out4] = sys_8e85562a050984b86e0fc574725998f0(in1val1,in2val1,in3val1,in4val1,in5val1,in6val1,in7val1)
%SYS_8E85562A050984B86E0FC574725998F0
%    [OUT1,OUT2,OUT3,OUT4,J_OUT1,J_OUT2,J_OUT3,J_OUT4,H_OUT1,H_OUT2,H_OUT3,H_OUT4] = SYS_8E85562A050984B86E0FC574725998F0(IN1VAL1,IN2VAL1,IN3VAL1,IN4VAL1,IN5VAL1,IN6VAL1,IN7VAL1)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    29-Mar-2022 00:00:50

out1 = 0.0;
if nargout > 1
    t2 = in2val1.^2;
    t3 = in3val1.^2;
    t4 = in4val1.^2;
    t5 = in5val1.^9;
    t6 = in5val1.^10;
    t7 = in7val1.^9;
    t8 = in7val1.^10;
    t10 = in1val1.*2.255769564462953e-5;
    t9 = t2+t3+t4;
    t16 = t10+1.0;
    t11 = 1.0./t9;
    t17 = 1.0./t16.^4.258643795229161;
    t18 = 1.0./t16.^5.258643795229161;
    t21 = 1.0./t16.^4.784508174752077e+1;
    t12 = t11.^2;
    t14 = t11.^11;
    t19 = t17.^10;
    t20 = t17.^11;
    t22 = in5val1.*t11.*t17.*5.856831421972189e-2;
    t23 = in7val1.*t11.*t17.*5.856831421972189e-2;
    t25 = in5val1.*in7val1.*t11.*t17.*(-5.856831421972189e-2);
    t32 = in5val1.*in7val1.*t11.*t18.*5.626376268150367e-6;
    t13 = t12.^5;
    t15 = t12.^6;
    t24 = in7val1.*t22;
    t26 = in2val1.*in5val1.*in7val1.*t12.*t17.*1.171366284394438e-1;
    t27 = in3val1.*in5val1.*in7val1.*t12.*t17.*1.171366284394438e-1;
    t28 = in4val1.*in5val1.*in7val1.*t12.*t17.*1.171366284394438e-1;
    t33 = -t32;
    t29 = -t26;
    t30 = -t27;
    t31 = -t28;
    et1 = t6.*t8.*t13.*t19;
    et2 = 1.296078973314911e-13;
    t34 = et1.*et2;
    t35 = cos(t34);
    t36 = sin(t34);
    t37 = in6val1.*t11.*t17.*t36.*5.856831421972189e-2;
    out2 = t24-t37;
end
if nargout > 2
    t38 = in2val1.*in6val1.*t12.*t17.*t36.*1.171366284394438e-1;
    t39 = in3val1.*in6val1.*t12.*t17.*t36.*1.171366284394438e-1;
    t40 = in4val1.*in6val1.*t12.*t17.*t36.*1.171366284394438e-1;
    t41 = in6val1.*t11.*t18.*t36.*5.626376268150367e-6;
    et3 = in6val1.*t5.*t8.*t14.*t20.*t35;
    et4 = 7.590916056268228e-14;
    t43 = et3.*et4;
    et5 = in6val1.*t6.*t7.*t14.*t20.*t35;
    et6 = 7.590916056268228e-14;
    t44 = et5.*et6;
    et7 = in2val1.*in6val1.*t6.*t8.*t15.*t20.*t35;
    et8 = 1.518183211253646e-13;
    t47 = et7.*et8;
    et9 = in3val1.*in6val1.*t6.*t8.*t15.*t20.*t35;
    et10 = 1.518183211253646e-13;
    t48 = et9.*et10;
    et11 = in4val1.*in6val1.*t6.*t8.*t15.*t20.*t35;
    et12 = 1.518183211253646e-13;
    t49 = et11.*et12;
    et13 = in6val1.*t6.*t8.*t14.*t21.*t35;
    et14 = 7.292227977107711e-18;
    t50 = et13.*et14;
    t42 = t25+t37;
    out3 = t42.^2.*(3.0./2.0e+1)+1.0./5.0e+1;
end
if nargout > 3
    out4 = 1.225225682761773./t17;
end
if nargout > 4
    j_out1 = [0.0,0.0,0.0,0.0,0.0,0.0,0.0];
end
if nargout > 5
    t45 = -t43;
    t46 = -t44;
    t53 = t29+t38+t47;
    t54 = t30+t39+t48;
    t55 = t31+t40+t49;
    t56 = t33+t41+t50;
    t51 = t22+t46;
    t52 = t23+t45;
    j_out2 = [t56,t53,t54,t55,t52,t11.*t17.*t36.*(-5.856831421972189e-2),t51];
end
if nargout > 6
    j_out3 = [t42.*t56.*(-3.0./1.0e+1),t42.*t53.*(-3.0./1.0e+1),t42.*t54.*(-3.0./1.0e+1),t42.*t55.*(-3.0./1.0e+1),t42.*t52.*(-3.0./1.0e+1),t11.*t17.*t36.*t42.*1.757049426591657e-2,t42.*t51.*(-3.0./1.0e+1)];
end
if nargout > 7
    j_out4 = [t16.^3.258643795229161.*1.17701538732318e-4,0.0,0.0,0.0,0.0,0.0,0.0];
end
if nargout > 8
    h_out1 = zeros(0,0);
end
if nargout > 9
    h_out2 = zeros(0,0);
end
if nargout > 10
    h_out3 = zeros(0,0);
end
if nargout > 11
    h_out4 = zeros(0,0);
end

end
