function [out1,out2,j_out1,j_out2,h_out1,h_out2] = sys_6d0c8d49e8ce128d1e58e7bc969babd9(in1val1,in2val1,in3val1,in4val1,in5val1)
%SYS_6D0C8D49E8CE128D1E58E7BC969BABD9
%    [OUT1,OUT2,J_OUT1,J_OUT2,H_OUT1,H_OUT2] = SYS_6D0C8D49E8CE128D1E58E7BC969BABD9(IN1VAL1,IN2VAL1,IN3VAL1,IN4VAL1,IN5VAL1)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    30-Mar-2022 23:21:22

t2 = in2val1.^2;
t3 = in3val1.^2;
t4 = in4val1.^2;
t6 = in1val1.*2.255769564462953e-5;
t7 = in1val1.*2.6117;
t5 = t2+t3+t4;
t9 = t6+1.0;
t12 = t7+1.1577867e+5;
t8 = sqrt(t5);
t11 = t9.^4.258643795229161;
t13 = 1.0./sqrt(t12);
t10 = 1.0./t8;
t14 = t8.*t13.*(3.0./1.0e+1);
t15 = t14+1.0;
out1 = in5val1.*t11.*t15.*8.453137041563874e+4;
if nargout > 1
    out2 = 2.138e-4;
end
if nargout > 2
    mt1 = [in5val1.*t9.^3.258643795229161.*t15.*8.120522209953342-in5val1.*t8.*t11.*t13.^3.*3.311558701717855e+4,in2val1.*in5val1.*t10.*t11.*t13.*2.535941112469162e+4,in3val1.*in5val1.*t10.*t11.*t13.*2.535941112469162e+4];
    mt2 = [in4val1.*in5val1.*t10.*t11.*t13.*2.535941112469162e+4,t11.*t15.*8.453137041563874e+4];
    j_out1 = reshape([mt1,mt2],1,5);
end
if nargout > 3
    j_out2 = [0.0,0.0,0.0,0.0,0.0];
end
if nargout > 4
    h_out1 = zeros(0,0);
end
if nargout > 5
    h_out2 = zeros(0,0);
end

end
