function [out1,j_out1,h_out1] = sys_5c3d0b6f83e157d7a11dd79fa014bdab(in1val1,in2val1,in3val1)
%SYS_5C3D0B6F83E157D7A11DD79FA014BDAB
%    [OUT1,J_OUT1,H_OUT1] = SYS_5C3D0B6F83E157D7A11DD79FA014BDAB(IN1VAL1,IN2VAL1,IN3VAL1)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    26-Mar-2022 22:16:04

t2 = in1val1.^2;
t3 = in2val1.^2;
t4 = in3val1.^2;
t5 = t2+t3+t4;
t6 = sqrt(t5);
out1 = [t6;t6;t6];
if nargout > 1
    t7 = 1.0./t6;
    t8 = in1val1.*t7;
    t9 = in2val1.*t7;
    t10 = in3val1.*t7;
    j_out1 = reshape([t8,t8,t8,t9,t9,t9,t10,t10,t10],[3,3]);
end
if nargout > 2
    h_out1 = zeros(0,0);
end

end
