function [out1,j_out1,h_out1] = sys_8eca6ff2f77a79b9aa1f3c57f0560a0a(in1,in2,in3)
%SYS_8ECA6FF2F77A79B9AA1F3C57F0560A0A
%    [OUT1,J_OUT1,H_OUT1] = SYS_8ECA6FF2F77A79B9AA1F3C57F0560A0A(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    04-Apr-2022 23:43:08

in2val4 = in2(4,:);
in2val5 = in2(5,:);
in2val6 = in2(6,:);
in2val7 = in2(7,:);
in2val8 = in2(8,:);
in2val9 = in2(9,:);
in2val10 = in2(10,:);
out1 = [in2val7.^2+in2val8.^2+in2val9.^2+in2val10.^2;sqrt(in2val4.^2+in2val5.^2+in2val6.^2)];
if nargout > 1
    j_out1 = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,in2val4.*1.0./sqrt(in2val4.^2+in2val5.^2+in2val6.^2),0.0,in2val5.*1.0./sqrt(in2val4.^2+in2val5.^2+in2val6.^2),0.0,in2val6.*1.0./sqrt(in2val4.^2+in2val5.^2+in2val6.^2),in2val7.*2.0,0.0,in2val8.*2.0,0.0,in2val9.*2.0,0.0,in2val10.*2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[2,29]);
end
if nargout > 2
    h_out1 = zeros(0,0);
end

end
