function [out1,j_out1,h_out1] = sys_7c5a7f11e09c96ffc470bf8746f230c3(in1,in2,in3)
%SYS_7C5A7F11E09C96FFC470BF8746F230C3
%    [OUT1,J_OUT1,H_OUT1] = SYS_7C5A7F11E09C96FFC470BF8746F230C3(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    05-Apr-2022 20:31:43

in2val4 = in2(4,:);
in2val5 = in2(5,:);
in2val6 = in2(6,:);
in2val7 = in2(7,:);
in2val8 = in2(8,:);
in2val9 = in2(9,:);
in2val10 = in2(10,:);
out1 = [in2val7.^2+in2val8.^2+in2val9.^2+in2val10.^2;sqrt(in2val4.^2+in2val5.^2+in2val6.^2)];
if nargout > 1
    j_out1 = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,in2val4.*1.0./sqrt(in2val4.^2+in2val5.^2+in2val6.^2),0.0,in2val5.*1.0./sqrt(in2val4.^2+in2val5.^2+in2val6.^2),0.0,in2val6.*1.0./sqrt(in2val4.^2+in2val5.^2+in2val6.^2),in2val7.*2.0,0.0,in2val8.*2.0,0.0,in2val9.*2.0,0.0,in2val10.*2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[2,26]);
end
if nargout > 2
    h_out1 = zeros(0,0);
end

end
