function [ constraintvalue, j_constraintvalue ] = mb_fm_mex_FBC(states, controls, constant_1)
%mb_fm_mex_FBC
% File automatically generated by FALCON.m

%=== Extract Data From Input ==============================================
x_E = states(1);
y_E = states(2);
z_E = states(3);
v = states(4);
e0 = states(5);
e1 = states(6);
e2 = states(7);
e3 = states(8);
W = states(9);
P = states(10);
Js = states(11);
n = states(12);
Pcom = controls(1);
Jscom = controls(2);
ncom = controls(3);

%=== Jacobians and Hessians ===============================================
j_states = zeros(12, 15);
j_states(:, 1 : 12) = eye(12);
j_x_E = j_states(1, :);
j_y_E = j_states(2, :);
j_z_E = j_states(3, :);
j_v = j_states(4, :);
j_e0 = j_states(5, :);
j_e1 = j_states(6, :);
j_e2 = j_states(7, :);
j_e3 = j_states(8, :);
j_W = j_states(9, :);
j_P = j_states(10, :);
j_Js = j_states(11, :);
j_n = j_states(12, :);
j_controls = zeros(3, 15);
j_controls(:, 13 : 15) = eye(3);
j_Pcom = j_controls(1, :);
j_Jscom = j_controls(2, :);
j_ncom = j_controls(3, :);

%=== Write Constants ======================================================

%=== Subsystem FBC ========================================================

% Defined at ?

% Call sys_5a3e1ea0ce79a4748bce5750a4ae9f28_jac
[ constraintvaluetmp, j_constraintvaluetmp ] = sys_5a3e1ea0ce79a4748bce5750a4ae9f28_jac(states, controls, constant_1);

% Hessian Jacobian for sys_5a3e1ea0ce79a4748bce5750a4ae9f28_jac
tmp_j_input_sys_5a3e1ea0ce79a4748bce5750a4ae9f28_jac = [j_states; j_controls];

% Calculation of Jacobian with respect to function global input for sys_5a3e1ea0ce79a4748bce5750a4ae9f28_jac
j_constraintvaluetmp = j_constraintvaluetmp * tmp_j_input_sys_5a3e1ea0ce79a4748bce5750a4ae9f28_jac;

% Combine Variables to constraintvalue
constraintvalue = [constraintvaluetmp];
j_constraintvalue = [
    j_constraintvaluetmp(1, :)
];

end
