function [out1,j_out1,h_out1] = sys_5a3e1ea0ce79a4748bce5750a4ae9f28_jac(in1,in2,ndIn1val1)
%SYS_5A3E1EA0CE79A4748BCE5750A4AE9F28_JAC
%    [OUT1,J_OUT1,H_OUT1] = SYS_5A3E1EA0CE79A4748BCE5750A4AE9F28_JAC(IN1,IN2,NDIN1VAL1)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    22-Mar-2023 14:08:11

%Generated using CreateGradient
%Input dimensions : {[12 1], [3 1], [1 1]}
%Derivative inputs: [true true false]
%DerivativeOrder  : 1
%Output dimensions: {[1 1]}
%Constant outputs : false
in1val3 = in1(3,:);
out1 = in1val3-ndIn1val1;
if nargout > 1
    j_out1 = [0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0];
end
if nargout > 2
    h_out1 = zeros(0,0);
end

end  % sys_5a3e1ea0ce79a4748bce5750a4ae9f28_jac
