function [out1,j_out1,h_out1] = sys_d65b7474b75607402bb5017bb9d762f1_jac(in1,in2,in3)
%SYS_D65B7474B75607402BB5017BB9D762F1_JAC
%    [OUT1,J_OUT1,H_OUT1] = SYS_D65B7474B75607402BB5017BB9D762F1_JAC(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    22-Mar-2023 13:58:13

%Generated using CreateGradient
%Input dimensions : {[12 1], [3 1], [12 1]}
%Derivative inputs: [true true false]
%DerivativeOrder  : 1
%Output dimensions: {[12 1]}
%Constant outputs : false
in1val1 = in1(1,:);
in1val2 = in1(2,:);
in1val3 = in1(3,:);
in1val4 = in1(4,:);
in1val5 = in1(5,:);
in1val6 = in1(6,:);
in1val7 = in1(7,:);
in1val8 = in1(8,:);
in1val9 = in1(9,:);
in1val10 = in1(10,:);
in1val11 = in1(11,:);
in1val12 = in1(12,:);
ndIn1val1 = in3(1,:);
ndIn1val2 = in3(2,:);
ndIn1val3 = in3(3,:);
ndIn1val4 = in3(4,:);
ndIn1val5 = in3(5,:);
ndIn1val6 = in3(6,:);
ndIn1val7 = in3(7,:);
ndIn1val8 = in3(8,:);
ndIn1val9 = in3(9,:);
ndIn1val10 = in3(10,:);
ndIn1val11 = in3(11,:);
ndIn1val12 = in3(12,:);
out1 = [in1val1-ndIn1val1;in1val2-ndIn1val2;in1val3-ndIn1val3;in1val4-ndIn1val4;in1val5-ndIn1val5;in1val6-ndIn1val6;in1val7-ndIn1val7;in1val8-ndIn1val8;in1val9-ndIn1val9;in1val10-ndIn1val10;in1val11-ndIn1val11;in1val12-ndIn1val12];
if nargout > 1
    j_out1 = reshape([1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[12,15]);
end
if nargout > 2
    h_out1 = zeros(0,0);
end

end  % sys_d65b7474b75607402bb5017bb9d762f1_jac
