function [ constraintvalue, j_constraintvalue ] = mb_fm_mex_sysConstraint(outputs, states, controls)
%mb_fm_mex_sysConstraint
% File automatically generated by FALCON.m

%=== Extract Data From Input ==============================================
phi = outputs(1);
gamma = outputs(2);
psi = outputs(3);
alpha = outputs(4);
CL = outputs(5);
CD = outputs(6);
T = outputs(7);
TSFC = outputs(8);
ng = outputs(9);
Wneg = outputs(10);
x_E = states(1);
y_E = states(2);
z_E = states(3);
v = states(4);
e0 = states(5);
e1 = states(6);
e2 = states(7);
e3 = states(8);
W = states(9);
P = states(10);
Js = states(11);
n = states(12);
Pcom = controls(1);
Jscom = controls(2);
ncom = controls(3);

%=== Jacobians and Hessians ===============================================
j_outputs = zeros(10, 25);
j_outputs(:, 1 : 10) = eye(10);
j_phi = j_outputs(1, :);
j_gamma = j_outputs(2, :);
j_psi = j_outputs(3, :);
j_alpha = j_outputs(4, :);
j_CL = j_outputs(5, :);
j_CD = j_outputs(6, :);
j_T = j_outputs(7, :);
j_TSFC = j_outputs(8, :);
j_ng = j_outputs(9, :);
j_Wneg = j_outputs(10, :);
j_states = zeros(12, 25);
j_states(:, 11 : 22) = eye(12);
j_x_E = j_states(1, :);
j_y_E = j_states(2, :);
j_z_E = j_states(3, :);
j_v = j_states(4, :);
j_e0 = j_states(5, :);
j_e1 = j_states(6, :);
j_e2 = j_states(7, :);
j_e3 = j_states(8, :);
j_W = j_states(9, :);
j_P = j_states(10, :);
j_Js = j_states(11, :);
j_n = j_states(12, :);
j_controls = zeros(3, 25);
j_controls(:, 23 : 25) = eye(3);
j_Pcom = j_controls(1, :);
j_Jscom = j_controls(2, :);
j_ncom = j_controls(3, :);

%=== Write Constants ======================================================

%=== Subsystem sysConstraint ==============================================

% Defined at ?

% Call sys_7940c2593334abb4279bf2c7ccd9b43c_jac
[ constraintvaluetmp, j_constraintvaluetmp ] = sys_7940c2593334abb4279bf2c7ccd9b43c_jac(outputs, states, controls);

% Hessian Jacobian for sys_7940c2593334abb4279bf2c7ccd9b43c_jac
tmp_j_input_sys_7940c2593334abb4279bf2c7ccd9b43c_jac = [j_outputs; j_states; j_controls];

% Calculation of Jacobian with respect to function global input for sys_7940c2593334abb4279bf2c7ccd9b43c_jac
j_constraintvaluetmp = j_constraintvaluetmp * tmp_j_input_sys_7940c2593334abb4279bf2c7ccd9b43c_jac;

% Combine Variables to constraintvalue
constraintvalue = [constraintvaluetmp];
j_constraintvalue = [
    j_constraintvaluetmp(1, :)
];

end
