function [ constraintvalue, j_constraintvalue ] = mb_fm_mex_sysConstraint(outputs, states, controls)
%mb_fm_mex_sysConstraint
% File automatically generated by FALCON.m

%=== Extract Data From Input ==============================================
phi_P = outputs(1);
gamma_P = outputs(2);
psi_P = outputs(3);
alpha = outputs(4);
CL = outputs(5);
CD = outputs(6);
T = outputs(7);
TSFC = outputs(8);
rho_P = outputs(9);
Omega1_P = outputs(10);
Omega2_P = outputs(11);
Omega3_P = outputs(12);
e0dot = outputs(13);
e1dot = outputs(14);
e2dot = outputs(15);
e3dot = outputs(16);
x_E = states(1);
y_E = states(2);
z_E = states(3);
vx_E = states(4);
vy_E = states(5);
vz_E = states(6);
e0 = states(7);
e1 = states(8);
e2 = states(9);
e3 = states(10);
W_P = states(11);
phidot_P = states(12);
Js_P = states(13);
n_P = states(14);
phidotcom_P = controls(1);
Jscom_P = controls(2);
ncom_P = controls(3);

%=== Jacobians and Hessians ===============================================
j_outputs = zeros(16, 33);
j_outputs(:, 1 : 16) = eye(16);
j_phi_P = j_outputs(1, :);
j_gamma_P = j_outputs(2, :);
j_psi_P = j_outputs(3, :);
j_alpha = j_outputs(4, :);
j_CL = j_outputs(5, :);
j_CD = j_outputs(6, :);
j_T = j_outputs(7, :);
j_TSFC = j_outputs(8, :);
j_rho_P = j_outputs(9, :);
j_Omega1_P = j_outputs(10, :);
j_Omega2_P = j_outputs(11, :);
j_Omega3_P = j_outputs(12, :);
j_e0dot = j_outputs(13, :);
j_e1dot = j_outputs(14, :);
j_e2dot = j_outputs(15, :);
j_e3dot = j_outputs(16, :);
j_states = zeros(14, 33);
j_states(:, 17 : 30) = eye(14);
j_x_E = j_states(1, :);
j_y_E = j_states(2, :);
j_z_E = j_states(3, :);
j_vx_E = j_states(4, :);
j_vy_E = j_states(5, :);
j_vz_E = j_states(6, :);
j_e0 = j_states(7, :);
j_e1 = j_states(8, :);
j_e2 = j_states(9, :);
j_e3 = j_states(10, :);
j_W_P = j_states(11, :);
j_phidot_P = j_states(12, :);
j_Js_P = j_states(13, :);
j_n_P = j_states(14, :);
j_controls = zeros(3, 33);
j_controls(:, 31 : 33) = eye(3);
j_phidotcom_P = j_controls(1, :);
j_Jscom_P = j_controls(2, :);
j_ncom_P = j_controls(3, :);

%=== Write Constants ======================================================

%=== Subsystem sysConstraint ==============================================

% Defined at ?

% Call sys_9bbbbd3c6987c2e9fd1e27f1b1183bfa_jac
[ constraintvaluetmp, j_constraintvaluetmp ] = sys_9bbbbd3c6987c2e9fd1e27f1b1183bfa_jac(outputs, states, controls);

% Hessian Jacobian for sys_9bbbbd3c6987c2e9fd1e27f1b1183bfa_jac
tmp_j_input_sys_9bbbbd3c6987c2e9fd1e27f1b1183bfa_jac = [j_outputs; j_states; j_controls];

% Calculation of Jacobian with respect to function global input for sys_9bbbbd3c6987c2e9fd1e27f1b1183bfa_jac
j_constraintvaluetmp = j_constraintvaluetmp * tmp_j_input_sys_9bbbbd3c6987c2e9fd1e27f1b1183bfa_jac;

% Combine Variables to constraintvalue
constraintvalue = [constraintvaluetmp];
j_constraintvalue = [
    j_constraintvaluetmp(1, :)
    j_constraintvaluetmp(2, :)
];

end
