function [out1,j_out1,h_out1] = sys_9bbbbd3c6987c2e9fd1e27f1b1183bfa_jac(in1,in2,in3)
%SYS_9BBBBD3C6987C2E9FD1E27F1B1183BFA_JAC
%    [OUT1,J_OUT1,H_OUT1] = SYS_9BBBBD3C6987C2E9FD1E27F1B1183BFA_JAC(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    17-Jan-2023 20:53:11

%Generated using CreateGradient
%Input dimensions : {[16 1], [14 1], [3 1]}
%Derivative inputs: [true true true]
%DerivativeOrder  : 1
%Output dimensions: {[2 1]}
%Constant outputs : false
in2val4 = in2(4,:);
in2val5 = in2(5,:);
in2val6 = in2(6,:);
in2val7 = in2(7,:);
in2val8 = in2(8,:);
in2val9 = in2(9,:);
in2val10 = in2(10,:);
out1 = [in2val7.^2+in2val8.^2+in2val9.^2+in2val10.^2;sqrt(in2val4.^2+in2val5.^2+in2val6.^2)];
if nargout > 1
    j_out1 = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,in2val4.*1.0./sqrt(in2val4.^2+in2val5.^2+in2val6.^2),0.0,in2val5.*1.0./sqrt(in2val4.^2+in2val5.^2+in2val6.^2),0.0,in2val6.*1.0./sqrt(in2val4.^2+in2val5.^2+in2val6.^2),in2val7.*2.0,0.0,in2val8.*2.0,0.0,in2val9.*2.0,0.0,in2val10.*2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[2,33]);
end
if nargout > 2
    h_out1 = zeros(0,0);
end

end  % sys_9bbbbd3c6987c2e9fd1e27f1b1183bfa_jac
