function [out1,j_out1,h_out1] = sys_9ff8e58f0805e65e943983fb2b87a95a(in1,in2,in3)
%SYS_9FF8E58F0805E65E943983FB2B87A95A
%    [OUT1,J_OUT1,H_OUT1] = SYS_9FF8E58F0805E65E943983FB2B87A95A(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    05-Jun-2022 20:41:14

in2val4 = in2(4,:);
in2val5 = in2(5,:);
in2val6 = in2(6,:);
out1 = sqrt(in2val4.^2+in2val5.^2+in2val6.^2);
if nargout > 1
    j_out1 = [0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,in2val4.*1.0./sqrt(in2val4.^2+in2val5.^2+in2val6.^2),in2val5.*1.0./sqrt(in2val4.^2+in2val5.^2+in2val6.^2),in2val6.*1.0./sqrt(in2val4.^2+in2val5.^2+in2val6.^2),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0];
end
if nargout > 2
    h_out1 = zeros(0,0);
end

end
