function [out1,j_out1,h_out1] = sys_771a4ce7b5f5597d2bc13c78dfb995d5(in1val1,in2val1,in3val1)
%SYS_771A4CE7B5F5597D2BC13C78DFB995D5
%    [OUT1,J_OUT1,H_OUT1] = SYS_771A4CE7B5F5597D2BC13C78DFB995D5(IN1VAL1,IN2VAL1,IN3VAL1)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    30-Mar-2022 19:47:01

out1 = [in1val1;in2val1;in3val1];
if nargout > 1
    j_out1 = reshape([1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0],[3,3]);
end
if nargout > 2
    h_out1 = zeros(0,0);
end

end
