function [out1,out2,j_out1,j_out2,h_out1,h_out2] = sys_8d7f8028440934d80e5e0c446ae346ac(in1val1,in2val1,in3val1,in4val1,in5val1)
%SYS_8D7F8028440934D80E5E0C446AE346AC
%    [OUT1,OUT2,J_OUT1,J_OUT2,H_OUT1,H_OUT2] = SYS_8D7F8028440934D80E5E0C446AE346AC(IN1VAL1,IN2VAL1,IN3VAL1,IN4VAL1,IN5VAL1)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    29-Mar-2022 23:10:12

t2 = in1val1.*2.255769564462953e-5;
t3 = t2+1.0;
t4 = t3.^4.258643795229161;
out1 = in5val1.*t4.*8.898038991119867e+4;
if nargout > 1
    out2 = 2.138e-4;
end
if nargout > 2
    j_out1 = [in5val1.*t3.^3.258643795229161.*8.54791811574036,0.0,0.0,0.0,t4.*8.898038991119867e+4];
end
if nargout > 3
    j_out2 = [0.0,0.0,0.0,0.0,0.0];
end
if nargout > 4
    h_out1 = zeros(0,0);
end
if nargout > 5
    h_out2 = zeros(0,0);
end

end
