function [out1,j_out1,h_out1] = sys_6660ca7b3a59f873d788ad4c209e1c7d_jac(in1val1,in2val1,in3val1,in4val1)
%SYS_6660CA7B3A59F873D788AD4C209E1C7D_JAC
%    [OUT1,J_OUT1,H_OUT1] = SYS_6660CA7B3A59F873D788AD4C209E1C7D_JAC(IN1VAL1,IN2VAL1,IN3VAL1,IN4VAL1)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    25-Jan-2023 22:41:47

%Generated using CreateGradient
%Input dimensions : {[1 1], [1 1], [1 1], [1 1]}
%Derivative inputs: [true true true true]
%DerivativeOrder  : 1
%Output dimensions: {[3 1]}
%Constant outputs : false
t2 = cos(in3val1);
t3 = cos(in4val1);
t4 = sin(in3val1);
t5 = sin(in4val1);
t6 = in1val1.*t2.*t3;
t7 = in1val1.*t2.*t5;
out1 = [t6;t7;-in1val1.*t4];
if nargout > 1
    j_out1 = reshape([t2.*t3,t2.*t5,-t4,0.0,0.0,0.0,-in1val1.*t3.*t4,-in1val1.*t4.*t5,-in1val1.*t2,-t7,t6,0.0],[3,4]);
end
if nargout > 2
    h_out1 = zeros(0,0);
end

end  % sys_6660ca7b3a59f873d788ad4c209e1c7d_jac
